version: '3.8'

services:
  server:
    build:
      context: ./chatapp
      dockerfile: Dockerfile
    image: backend
    volumes: 
      - ./chatapp/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    networks:
      - app-network


  frontend:
    build:
      context: ./chatappfront
      dockerfile: Dockerfile
    image: frontend
    volumes:
      - ./chatappfront/:/usr/src/app
      - ./usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  node_modules:
networks:
      app-network:
        driver: bridge